#!/bin/sh
#
# @name HexOverride
#
# @type Hex Override
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 servo 1
# @output MAIN8 servo 2
#
#
# @maintainer Hayley LeBlanc <hayley@sicdrone.com>
# @maintainer Alex Michel <alex@sicdrone.com>
#

sh /etc/init.d/rc.mc_defaults

set MIXER hex_override

# Need to set all 8 channels
set PWM_OUT 12345678
